### PR TITLE
refactor(aot): replace robotjs with electron screen api

### PR DESCRIPTION
**Pull request by csett86**
robotjs has no support on wayland, replace with electron native api

### CODE REVIEW

**Comment by csett86** [comment]
@saghul Please review. I have tested this successfully and as robotjs is not context-aware, it is not compatible with Electron 14+, thus replace it as best as possible.

**Comment by saghul** [comment]
Nice! We have 8x8 apps using this package, so we can't just require Electron 14.

I think we could make this the 3.0 release.

@hristoterezov thoughts?

@csett86 I'm quite busy these days, I'll try to get to this PR next week or the one after. I think we also have some remote module usages here that prevent us from using 14, don't we?

**Comment by csett86** [comment]
Yes, you are totally right, the contect-aware topic is not the only (and probably the smaller) issue.

I was planning to tackle the other obstacles for electron 14 in separate PRs as well.

**Comment by saghul** [comment]
> I was planning to tackle the other obstacles for electron 14 in separate PRs as well.

Sounds like a plan!

**Comment by csett86** [comment]
No longer necessary after #129, closing

**Pull request closed without merging**
