### PR TITLE
BREAKING CHANGE: replace remote module in remotecontrol for electron 14+

### PR DESCRIPTION
**Pull request by csett86**
Now requires are component running on main process, thus breaking existing API, thus major version bump included as well.

Closes: #126

### CODE REVIEW

**Comment by csett86** [comment]
I already tested it successfully on Linux and Mac, Windows testing in progress

**Comment by csett86** [comment]
@saghul, @quitrk: Successfully tested on Windows, Linux and Mac, please review together with https://github.com/jitsi/jitsi-meet-electron/pull/655

**Review by saghul — APPROVED** [review]
LGTM. I see we still have robotjs in there, wasn't that going away too?

**Comment by csett86** [comment]
aot had a single use of robotjs that could be easily replaced, but remotecontrol unfortunately uses a lot more apis of robotjs. And its not strictly necessary to replace, as it works with electron 14+ as long as it is made context-aware.

**Pull request merged**
