### PR TITLE
Remove mac-screen-capture-permissions

### PR DESCRIPTION
**Pull request by csett86**
mac-screen-capture-permissions prevents successful notarization for Big Sur:
https://github.com/karaggeorge/mac-screen-capture-permissions/issues/5

Screensharing continues to work with Electron 11, the question to enable screen
recording permission is just moved to the first instance of screensharing
instead of first launch.

Signed-off-by: Christoph Settgast <csett86@web.de>

### CODE REVIEW

**Comment by csett86** [comment]
Even with perfectly signed and notarized .app the following error will otherwise appear on Big Sur:

Bildschirmfoto 2021-01-04 um 16 20 55

As the libary is not necessary for successful screenshare, remove it.

**Comment by csett86** [comment]
@saghul any chance to get this reviewed? mac-screen-capture-permissions is blocking both an M1 version of the Jitsi electron app (as the unnecessary dependency contains an x86 binary and no rebuild instructions) and prevents successful notarization check on Big Sur. 

I would prefer to drop my own fork (https://github.com/csett86/jitsi-meet-electron-utils) rather sooner than later :)

**Comment by saghul** [comment]
Hum, the problem I see here is that we are no longer able to reset the permissions so the system prompt won't show again, leaving the users with no clue about what to do. IIRC that was the main reason why we introduced the module.

The proper fix would probably be to build the mac-screen-capture-permissions library with an arm64 slice too, as a "fat binary".

Or drop this library and use some other way to accomplish the same, but as it stands I cannot accept this PR, sorry.

**Comment by csett86** [comment]
I understand and I gave it some more thought. I have replaced the bundled executable in mac-screen-capture-permissions with a n-api native module that does the same thing: https://github.com/karaggeorge/mac-screen-capture-permissions/pull/6

Hopefully this can get merged, then a new release cut for mac-screen-capture-permissions, and then updated here in jitsi-meet-electron-utils.

**Comment by saghul** [comment]
Excellent work!

**Pull request closed without merging**
