### PR TITLE
feat(wifistats): Change to sync write in iframe window object

### PR DESCRIPTION
**Pull request by gimre**

### CODE REVIEW

**Comment by damencho** [comment]
Does this change affects jitsi-meet-electron? I mean have you tested it there, maybe after this change we need to add the load listener there, if there are cases which brakes it?

**Comment by gimre** [comment]
@damencho it shouldn't affect anything, but I wrote to @hristoterezov and hopefully he can test it in jitsi-meet-electron to confirm

**Comment by damencho** [comment]
One more question, why this listener works for always on top, remote control, and screen sharing but will not work with wifi stats?

**Comment by hristoterezov** [comment]
I guess the listener handles reloads of the iframe due to non-recoverable errors. IMHO the listener have to be there and in addition we should execute it or add into the docs that the function needs to be called before the iframe is loaded.

**Comment by gimre** [comment]
talked to @hristoterezov and he will be implementing a more robust solution. closing for now

**Pull request closed without merging**
