### PR TITLE
Fix error with mouse moving in Windows with multiple displays

### PR DESCRIPTION
**Pull request by vyatkin0**
There is a error in robotjs that causes incorrect mouse position in Windows 10 with multiple displays.
RobotJS doesn't  work when displays have different dpi or placed on virtual screen randomly.

### CODE REVIEW

**Comment by saghul** [comment]
Thanks Aleksey! @hristoterezov can you PTAL?

**Comment by vyatkin0** [comment]
The problem with screen sharing is still exists. Jitsi reports wrong display number to the remote control in Windows. For example, it shares display 0 but reports to remote control that display 1 is shared. The problem is related to electron->chromium->webrtc framework and solved in electron 3.0 beta2. With the latest version with electron Jitsi works well.

**Comment by hristoterezov** [comment]
@vyatkin0 Have you tested with the latest versions jitsi-meet-electron-utils?

**Comment by saghul** [comment]
No follow-up, closing.

**Pull request closed without merging**
